### ISSUE TITLE
你好，请问这是否没有用到rating（电影评分）这个数据

### ISSUE THREAD

**Issue by iamdawn** [xingzhexiaozhu/MovieRecommendation#2]

**Comment by xingzhexiaozhu** [comment]
您好，这个程序只是当时研究时写的一个简易小程序，没有精确到用户对电影打多少分进而产生推荐；
这个简易代码可以由人为设置兴趣阈值-基于简单的是不是感兴趣-找到推荐目标；
所以，引入具体分数-基于具体分数产生推荐也可以优化试试看效果
