### ISSUE TITLE
关于一些问题

### ISSUE THREAD

**Issue by unrealMJ** [xingzhexiaozhu/MovieRecommendation#6]
你好！非常感谢你的代码。但是我认为你的代码中有一些错误。
第一，在recommend（）函数中，rank[movie] += wuv这一句有问题，缺少用户对电影的评分。
第二，在计算指标时（以准确率为例），不能根据测试用户是否观看过所推荐的电影作为分子，造成指标偏低。

**Comment by xingzhexiaozhu** [comment]
谢谢您、很认真。之前也解释过，这里再解释一下哈，这个代码是几年前我自己探索这块内容时写的，在这个demo中并没有加入电影分数这个指标，所以大家感兴趣的话，可以在这个基础上做优化
